apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- manifests/namespace.yaml
- github.com/argoproj/argo-cd//manifests/cluster-install

patchesJson6902:
- path: patches/argocd-server-service.yaml
  target:
    version: v1
    kind: Service
    name: argocd-server
    namespace: argocd
